'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./plantsim-engine.js');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
function ready(){const p=E.newProject();E.importFiles(p);E.resolveConflict(p.versions[0],3);E.confirmBaseline(p,p.versions[0]);E.saveGoal(p,E.parseGoal(E.DEFAULT_TEXT));p.cards.forEach(E.freezeCard);return p;}
test('20 records, four regions, unique IDs',()=>{assert.equal(E.PLANTS.length,20);assert.equal(new Set(E.PLANTS.map(x=>x.id)).size,20);for(const a of ['入口区','滨水区','步道区','休息区'])assert.equal(E.PLANTS.filter(x=>x.area===a).length,5);});
test('Input Gate blocks unresolved conflicts and missing imports',()=>{const p=E.newProject(),v=p.versions[0];assert.throws(()=>E.confirmBaseline(p,v));assert.throws(()=>E.newRun(p,v));E.importFiles(p);assert.throws(()=>E.confirmBaseline(p,v));E.resolveConflict(v,3);E.confirmBaseline(p,v);assert.throws(()=>E.newRun(p,v));});
test('Goal versions immutable, task editing invalidates Gate',()=>{const p=ready(),g=JSON.stringify(p.goals[0]);E.saveGoal(p,{...E.parseGoal('未来2年遮阴70%'),focus:['健康']});assert.equal(JSON.stringify(p.goals[0]),g);assert.equal(p.goals.length,2);assert.equal(p.goals[1].horizon,24);const c=p.cards[0];E.validateCard(c);E.updateCard(c,{conditions:'夏季+4°C'});assert.equal(c.gate,null);E.freezeCard(c);assert.throws(()=>E.updateCard(c,{horizon:0}));assert.throws(()=>E.newRun(p,p.versions[0]));});
test('Six paths have independent baseline/state references',()=>{const p=ready(),r=E.newRun(p,p.versions[0]);assert.equal(r.paths.length,6);assert.notEqual(r.paths[0].state,r.paths[1].state);assert.notEqual(r.paths[0].state[0],r.paths[1].state[0]);const other=JSON.stringify(r.paths[1].state);r.paths[0].state[0].health=1;assert.equal(JSON.stringify(r.paths[1].state),other);assert.equal(p.versions[0].baseline.plants[0].health,undefined);});
test('Agents are read-only, changes are Resolver-owned and traceable',()=>{const p=ready(),r=E.newRun(p,p.versions[0]),path=r.paths[0],before=JSON.stringify(path.state);E.agents(r,path);assert.equal(JSON.stringify(path.state),before);E.tick(r);const h=path.history[0],effects=[...h.effects,...h.maintenance];for(const c of h.changes){assert.ok(effects.some(e=>e.id===c.effectId));assert.ok(Math.abs(c.after-c.before-c.delta)<1e-8);}const mid=E.StateResolver(h.input,h.effects),end=E.StateResolver(mid.state,h.maintenance);assert.deepEqual(end.state,h.state);});
test('All four Gate cases preserve completed agents and restore local node',()=>{const p=ready(),r=E.newRun(p,p.versions[0]);for(let i=0;i<60&&r.status!=='complete';i++){E.tick(r);for(const f of r.failures.filter(f=>f.status==='FAILED')){const path=r.paths.find(p=>p.id===f.pathId),history=JSON.stringify(path.history),others=path.pending.effects.filter(e=>e.agent==='Plant').map(E.clone),count=r.logs.filter(e=>e.type==='Agent').length;E.repair(r,f.id);assert.equal(JSON.stringify(path.history),history);assert.equal(JSON.stringify(path.pending.effects.filter(e=>e.agent==='Plant')),JSON.stringify(others));assert.equal(r.logs.filter(e=>e.type==='Agent').length,count);assert.equal(f.retry,1);assert.deepEqual(f.stages,['FAILED','LOCATING','MIN_ROLLBACK','REPAIRING','VALIDATING','RESUME']);}}assert.equal(r.status,'complete');assert.deepEqual(r.failures.map(f=>f.type),['Spatial','Schema','Business','Numeric']);assert.ok(r.logs.filter(x=>x.type==='ToolRetry').every(x=>x.data.quiet));});
test('Retry limit does not loop indefinitely',()=>{const p=ready(),r=E.newRun(p,p.versions[0]);for(let i=0;i<3;i++)E.tick(r);const f=r.failures[0];f.retry=2;assert.throws(()=>E.repair(r,f.id),/2次/);assert.equal(r.status,'failed');});
const p=ready(),r1=E.complete(E.newRun(p,p.versions[0]));
test('Differentiated six-path full-cycle risk evidence',()=>{assert.ok(r1.paths.every(x=>x.cycle===36&&x.history.length===36));const e=E.evaluate(r1),a=e.perPath.find(p=>p.pathId==='A1');assert.equal(a.exposure,0);for(const id of ['B1','B2','C1'])assert.ok(e.perPath.find(p=>p.pathId===id).exposure>5);assert.ok(r1.paths.flatMap(p=>p.history).some(h=>h.effects.some(e=>e.graphEdgeIds?.length)));});
test('Every Effect has an unambiguous unique ID',()=>{const ids=r1.paths.flatMap(p=>p.history.flatMap(h=>[...h.effects,...h.maintenance].map(e=>e.id)));assert.equal(new Set(ids).size,ids.length);});
test('Structured environment changes results and preserves run snapshots',()=>{const p=ready(),c=p.cards.find(c=>c.pathId==='B1');c.frozen=false;const environment=E.domain.environment('A1');environment.pathId='B1';E.updateCard(c,{environment});E.freezeCard(c);const r=E.complete(E.newRun(p,p.versions[0]));assert.ok(E.evaluate(r).perPath.find(p=>p.pathId==='B1').health>E.evaluate(r1).perPath.find(p=>p.pathId==='B1').health+20);assert.notDeepEqual(c.environment,r1.cards.find(c=>c.pathId==='B1').environment);});
test('Create V2/V3/V4 without changing old designs or results',()=>{E.evaluate(r1);const before=JSON.stringify(r1),v1=JSON.stringify(p.versions[0]);const v2=E.createVersion(p,p.versions[0],{note:'替换'});assert.equal(v2.id,'V2');assert.equal(v2.baseline.confirmed,false);assert.equal(v2.baseline.plants[0].name,'火焰木');E.confirmBaseline(p,v2);E.complete(E.newRun(p,v2,r1));const v3=E.createVersion(p,v2,{comprehensive:true,spacing:3});E.confirmBaseline(p,v3);E.complete(E.newRun(p,v3,r1));assert.equal(E.createVersion(p,v3).id,'V4');assert.equal(JSON.stringify(p.versions[0]),v1);assert.equal(JSON.stringify(r1),before);});
test('Fair comparison uses actual metrics, fixed seed/rules/conditions',()=>{const rows=E.compare(p.runs);assert.equal(rows.length,3);assert.notEqual(E.evaluate(p.runs[0]).values.exposure,E.evaluate(p.runs[2]).values.exposure);assert.ok(rows[0].health<rows[2].health);assert.ok(rows[0].construction<rows[2].construction);const bad=E.clone(p.runs[1]);bad.fairness+='changed';assert.throws(()=>E.compare([r1,bad]));assert.throws(()=>E.compare([r1]));});
test('Checkpoint replay produces separate run without touching original',()=>{const before=JSON.stringify(r1),r=E.replay(p,r1,'B2',12);assert.equal(r.paths[0].cycle,11);assert.equal(r.replayOf.runId,r1.id);E.complete(r);assert.equal(r.paths[0].cycle,36);assert.equal(JSON.stringify(r1),before);assert.deepEqual(r.paths[0].state,r1.paths.find(p=>p.id==='B2').state);assert.throws(()=>E.compare([r1,r]));});
test('Reset is a clean project; no shared state across sessions',()=>{const fresh=E.newProject();assert.equal(fresh.runs.length,0);assert.equal(fresh.versions.length,1);assert.equal(fresh.versions[0].baseline.confirmed,false);assert.equal(fresh.imports.length,0);});
test('HTML contains matching inline sources and no external resources',()=>{const html=fs.readFileSync('plantsim-demo.html','utf8');for(const f of ['plantsim-domain.js','plantsim-business.js','plantsim-engine.js','plantsim-ui.js'])assert.ok(html.includes(fs.readFileSync(f,'utf8').trim()));const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,4);scripts.forEach(m=>new Function(m[1]));assert.doesNotMatch(html,/<(?:script|link|img)[^>]+(?:src|href)=["']https?:/i);assert.doesNotMatch(html,/\bfetch\(|XMLHttpRequest/);});

test('Five dimensions have 20 auditable tool computations, no total score',()=>{const e=E.evaluate(r1);assert.equal(e.dimensions.length,5);assert.equal(e.calls.length,20);assert.equal(e.score,undefined);for(const c of e.calls){assert.ok(c.id&&c.formula&&c.input.runId&&c.evidence.plant);assert.equal(c.weight,.25);}const before=JSON.stringify(r1.paths),spec=E.clone(r1.evaluationSpec);spec.dimensions[0][2][0][5]=200;E.evaluate(r1,spec);assert.equal(JSON.stringify(r1.paths),before);});
test('Invalid monthly environment cannot freeze or start',()=>{const p=ready(),c=p.cards[0];c.frozen=false;E.updateCard(c,{environment:{...c.environment,months:[]}});assert.equal(E.validateCard(c).passed,false);assert.throws(()=>E.freezeCard(c));assert.throws(()=>E.newRun(p,p.versions[0]));});
test('Every plant is represented in graph and versions have isolated coordinates',()=>{for(const plant of E.PLANTS)assert.ok(E.domain.graph.nodes.some(n=>n.id===plant.id));const [a,b,c]=p.versions;assert.notDeepEqual(a.baseline.plants.map(x=>[x.x,x.y]),b.baseline.plants.map(x=>[x.x,x.y]));assert.notDeepEqual(b.baseline.plants.map(x=>[x.x,x.y]),c.baseline.plants.map(x=>[x.x,x.y]));});
test('Upgrade fragment is fully embedded without stale source',()=>{assert.ok(fs.readFileSync('plantsim-ui.js','utf8').includes(fs.readFileSync('plantsim-upgrade.js','utf8').trim()));assert.doesNotMatch(fs.readFileSync('plantsim-demo.html','utf8'),/<<<<<<<|=======|>>>>>>>/);});
console.log('\\n'+passed+' checks passed.');
