'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./plantsim-engine.js'),B=E.business;
let checks=0;function test(name,f){f();console.log('PASS',name);checks++;}
const p=E.newProject();E.importFiles(p);E.resolveConflict(p.versions[0],3);E.confirmBaseline(p,p.versions[0]);E.saveGoal(p,E.parseGoal(E.DEFAULT_TEXT));p.cards.forEach(E.freezeCard);
const r1=E.complete(E.newRun(p,p.versions[0])),v2=E.createVersion(p,p.versions[0],{strategy:'balanced'});E.confirmBaseline(p,v2);const r2=E.complete(E.newRun(p,v2,r1)),v3=E.createVersion(p,v2,{strategy:'resilient'});E.confirmBaseline(p,v3);const r3=E.complete(E.newRun(p,v3,r1));
test('V2 affects all four regions; V3 adds executable facilities',()=>{for(const area of ['入口区','滨水区','步道区','休息区'])assert.notEqual(JSON.stringify(p.versions[0].baseline.plants.filter(x=>x.area===area)),JSON.stringify(v2.baseline.plants.filter(x=>x.area===area)));assert.ok(v3.baseline.plants.some(x=>x.drainage));assert.ok(v3.baseline.plants.some(x=>x.windSupport));assert.ok(v3.emergencyWater>0);assert.notDeepEqual(r2.paths.find(x=>x.id==='C1').state,r3.paths.find(x=>x.id==='C1').state);});
test('Construction bills reconcile and snapshots remain independent',()=>{for(const r of [r1,r2,r3])assert.equal(r.design.cost,r.design.costItems.reduce((n,i)=>n+i.quantity*i.unitPrice,0));const saved=r1.design.cost;v2.costItems[0].amount++;assert.equal(r1.design.cost,saved);v2.costItems[0].amount--;});
test('Cost breakdown equals evaluation total, by path and all paths',()=>{for(const r of [r1,r2,r3]){const c=B.costs(r);assert.ok(Math.abs(c.construction+c.maintenance+c.rework-E.evaluate(r).total)<1e-6);assert.equal(c.maintenance,c.categories.reduce((n,x)=>n+x.amount,0));const by=r.paths.map(p=>B.costs(r,p.id));assert.ok(Math.abs(by.reduce((n,x)=>n+x.maintenance,0)/6-c.maintenance)<1e-6);assert.ok(c.categories.flatMap(x=>x.records).every(x=>x.decision==='执行'));}});
test('Completion requires actual adoption and excludes replay',()=>{assert.throws(()=>B.archive(p));p.adoption={versionId:'V3',runId:r3.id,note:'接受建设投入，改善极端风险'};assert.deepEqual(B.completionIssues(p),[]);p.adoption.note=' ';assert.throws(()=>B.archive(p));p.adoption.note='接受成本取舍';});
const item=B.archive(p),memory={raw:null,getItem(){return this.raw;},setItem(k,v){this.raw=v;},removeItem(){this.raw=null;}};
test('Compact archive fits local storage and omits full Trace',()=>{const bytes=Buffer.byteLength(JSON.stringify(item),'utf16le');console.log('Archive bytes (UTF16):',bytes);assert.ok(bytes<4.8*1024*1024);assert.ok(item.project.runs.every(r=>r.logs.length===0&&r.paths.every(p=>p.history.every(h=>!h.effects&&!h.checkpoint))));});
test('Saving, reopening and repeated completion do not duplicate value',()=>{let records=B.save(memory,[],item);records=B.save(memory,records,item);assert.equal(records.length,1);assert.equal(B.load(memory).length,1);const totals=B.totals(records);assert.equal(totals.count,4);assert.equal(totals.cost,B.CASES.reduce((n,x)=>n+x.cost,0)+item.contribution.cost);const restored=B.restore(B.load(memory)[0]);assert.equal(restored.status,'completed');assert.equal(E.evaluate(E.latestRun(restored,'V3')).total,E.evaluate(r3).total);assert.throws(()=>E.createVersion(restored,restored.versions[2]));assert.equal(B.costs(E.latestRun(restored,'V3')).maintenance,B.costs(r3).maintenance);});
test('Negative savings and estimated hours use signed source values',()=>{assert.equal(item.contribution.cost,E.evaluate(r1).total-E.evaluate(r3).total);assert.equal(item.contribution.hours,28);assert.ok(B.CASES.every(x=>x.cost===x.baseCost-x.chosenCost));});
test('Storage failure does not change archive or completion state',()=>{const bad={setItem(){throw Error('QuotaExceeded');}};const records=[item];assert.throws(()=>B.save(bad,records,item));assert.equal(records.length,1);assert.equal(p.status,'active');assert.throws(()=>B.load({getItem(){return '{broken';}}));});
test('Archive may be optimized without overwriting original conclusion',()=>{const before=JSON.stringify(item),restored=B.restore(item);restored.status='active';restored.adoption=null;const v=E.createVersion(restored,restored.versions[2],{strategy:'resilient'});E.confirmBaseline(restored,v);const r=E.newRun(restored,v,E.latestRun(restored,'V1'));assert.equal(r.seed,r1.seed);assert.equal(r.fairness,r1.fairness);assert.equal(JSON.stringify(item),before);});
test('Presentation sources and styles are embedded; removed footer absent',()=>{const ui=fs.readFileSync('plantsim-ui.js','utf8'),html=fs.readFileSync('plantsim-demo.html','utf8');assert.ok(ui.includes(fs.readFileSync('plantsim-presentation.js','utf8').trim()));assert.ok(html.includes(fs.readFileSync('plantsim-presentation.css','utf8').trim()));assert.doesNotMatch(html,/<p class="disclaimer">/);assert.ok(ui.includes('完成项目，返回工作台'));});
console.log(checks+' business checks passed.');
