/* Spatial simulation, environmental scenarios, executable knowledge graph and evaluation tools.
 * All coefficients are versioned demonstration assumptions, not calibrated botanical science. */
(function(root){'use strict';
function PlantSimDomain(C){
const {clone,PLANTS,PATHS,rng,effect}=C,clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x)),mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const SITE={width:760,height:400,metersPerUnit:.25,label:'3.2ha项目内的局部评测窗口；示意坐标，非测绘成果',roads:[125,210],waterline:310};
const RULE='eco-demo-3.0',SOURCE='专家待校准演示规则；PRD 4.6 / 7.1（业务口径）';
const units={maxC:'°C',meanC:'°C',rainMm:'mm/月',heatDays:'天/月',dryDays:'天',humidity:'%',soilMoisture:'%',waterloggingHours:'小时',gustMs:'m/s',visitors:'人/日',trampling:'0–1',diseasePressure:'0–1'};
function environment(id,horizon=36){return {schemaVersion:'environment-3',pathId:id,units,source:SOURCE,ruleVersion:RULE,seed:9032026,spatialScope:['入口区','滨水区','步道区','休息区'],susceptible:['A01','A03','B01','B05','C01','C02','D01','D04'],maintenance:{budget:1800,waterM3:id==='B1'?4:12,laborHours:24},months:Array.from({length:horizon},(_,i)=>{const m=i%12,c=i+1,summer=m>=4&&m<=8,spring=m>=2&&m<=4;let x={cycle:c,meanC:[18,19,22,25,28,30,31,31,29,26,22,19][m],maxC:[23,25,28,31,33,34,35,35,33,30,27,24][m],rainMm:[65,85,120,170,230,260,240,220,170,100,70,55][m],heatDays:summer?2:0,dryDays:5,humidity:72,soilMoisture:58,waterloggingHours:0,gustMs:10,visitors:1000,trampling:.12,diseasePressure:.06,event:'季节常态'};
if(id==='A2'&&[5,6,17,18,29,30].includes(c)){Object.assign(x,{maxC:37,heatDays:8,dryDays:12,soilMoisture:43,visitors:2400,trampling:.36,event:'短时热浪与客流脉冲'});}
if(id==='A3'&&(spring||summer)){Object.assign(x,{maxC:x.maxC+4,heatDays:summer?17:5,dryDays:spring?25:30,rainMm:x.rainMm*.4,soilMoisture:spring?25:18,event:spring?'春季水分亏缺':'春旱累积＋高温'});}
if(id==='B1'&&(summer||m===9)){Object.assign(x,{meanC:x.meanC+4,maxC:x.maxC+7,heatDays:24,dryDays:36,rainMm:x.rainMm*.23,soilMoisture:16,humidity:48,event:'持续热浪＋供水不足'});}
if(id==='B2'){Object.assign(x,{maxC:x.maxC+(summer?5:2),heatDays:summer?18:3,dryDays:summer?16:8,soilMoisture:summer?35:51,humidity:91,diseasePressure:summer?1:.4,event:summer?'高温高湿＋病害传播':'病原持续暴露'});}
if(id==='C1'){Object.assign(x,{maxC:x.maxC+(summer?4:0),heatDays:summer?14:0,visitors:summer?6500:3000,trampling:summer?.85:.5,diseasePressure:.15});if([7,8,19,20,28,31].includes(c))Object.assign(x,{gustMs:45,waterloggingHours:72,rainMm:420,humidity:92,event:'台风＋积水＋根系暴露'});else x.event='高客流与慢性踩踏';}
return x;})};}
function describe(env,cycle){const m=env.months.find(x=>x.cycle===cycle)||env.months[0];return `第${Math.floor((m.cycle-1)/12)+1}年${(m.cycle-1)%12+1}月：${m.event}。最高温${m.maxC}°C，热浪${m.heatDays}天；降水${Math.round(m.rainMm)}mm、连续干旱${m.dryDays}天，土壤含水${m.soilMoisture}%。湿度${m.humidity}%，积水${m.waterloggingHours}小时；阵风${m.gustMs}m/s；日均人流${m.visitors}人，踩踏指数${m.trampling}，病害压力${m.diseasePressure}。月养护上限¥${env.maintenance.budget} / ${env.maintenance.waterM3}m³水 / ${env.maintenance.laborHours}工时。`;}
const factors=[['heat','高温热浪','环境'],['drought','土壤水分亏缺','环境'],['humidity','空气湿度','环境'],['rain','降雨积水','环境'],['wind','台风阵风','环境'],['disease','病原压力','病害'],['leafspot','叶斑病','病害'],['rot','根腐','病害'],['aphid','蚜虫/煤污病','病害'],['crowd','人流强度','人流'],['trample','踩踏压实','人流'],['shade','遮阳降温','养护'],['irrigate','应急灌溉','养护'],['drain','排水疏通','养护'],['pest','病害隔离防治','养护'],['support','支撑修剪','养护'],['protect','围栏根系保护','养护'],['mulch','覆盖保湿','养护'],['inspect','巡检复核','养护'],['decline','健康持续衰退','风险'],['collapse','结构失稳','风险'],['gap','遮阴空间缺口','风险']];
const graph={version:RULE,nodes:[...PLANTS.map(p=>({id:p.id,label:p.name,type:'植物',area:p.area})),...factors.map(x=>({id:x[0],label:x[1],type:x[2]})),...['入口区','滨水区','步道区','休息区'].map((a,i)=>({id:'site'+i,label:a,type:'场地'}))],edges:[]};
function edge(id,from,to,relation,strength,condition,lag=0,paths=PATHS.map(p=>p.id)){graph.edges.push({id,from,to,relation,strength,condition,lagMonths:lag,paths,source:SOURCE});}
edge('heat-water','heat','drought','促进',.7,'热浪天数>10，蒸散加剧',1);edge('wet-fungus','humidity','leafspot','促进',.9,'湿度>80%，存在易感植物');edge('pest-disease','aphid','disease','促进',.65,'虫害压力>0.3');edge('rain-rot','rain','rot','促进',.85,'积水>24小时',1);edge('human-root','crowd','trample','暴露',.8,'日均客流>2000');edge('wind-fail','wind','collapse','促进',.9,'阵风>25m/s且根系受损');edge('decline-gap','decline','gap','促进',.8,'健康<40，冠幅退化',1);
for(const [a,b,w]of [['shade','heat',.6],['irrigate','drought',.7],['mulch','drought',.4],['drain','rain',.65],['pest','disease',.7],['support','wind',.55],['protect','trample',.75]])edge(a+'-'+b,a,b,'缓解',w,'措施执行且资源充足',1);
PLANTS.forEach((p,i)=>{edge('site-'+p.id,'site'+Math.floor(i/5),p.id,'暴露',1,'位于对应区域');for(const f of ['heat','drought','disease','wind','trample','rain'])edge(f+'-'+p.id,f,p.id,'易感',.65+(i%4)*.15,'压力与物种耐受阈值共同决定',f==='drought'?1:0);edge('decline-'+p.id,p.id,'decline','促进',1,'健康连续下降或高风险');if(i%5!==4)edge('spread-'+p.id,p.id,PLANTS[i+1].id,'传播',.7,'距离<12m，湿度>80%，邻株有感染',1,['B2','C1']);});
const weight=id=>graph.edges.find(e=>e.id===id)?.strength||1;
function layout(v,base,patch={}){v.layoutChanges=[];const move=(id,dx,dy)=>{const p=v.baseline.plants.find(x=>x.id===id);if(!p)return;const from={x:p.x,y:p.y};p.x=clamp(p.x+dx,20,740);p.y=clamp(p.y+dy,35,370);v.layoutChanges.push({plant:id,type:'移动',from,to:{x:p.x,y:p.y},reason:patch.note||'降低道路与水岸暴露'});};if(base){move('A01',28,-12);move('A02',-22,-9);move('A03',12,8);v.layoutChanges.push({plant:'A01',type:'替换',from:base.baseline.plants[0].name,to:v.baseline.plants[0].name,reason:'演示物种参数调整'});if(patch.comprehensive){move('B03',-32,-22);move('B04',20,-15);move('C01',35,-25);move('C02',-20,-15);move('D01',20,-12);const c=v.baseline.plants.find(x=>x.id==='C01');c.companionPoint={x:c.x+35,y:c.y+9,label:'樟树×2'};v.layoutChanges.push({plant:'C01',type:'新增',to:c.companionPoint,reason:'补植遮阴缺口'},{plant:'B03',type:'减少',from:15,to:10,reason:'降低局部密度，增设滴灌'});}}v.spatial={...SITE};return v;}
function spatial(p,state){const road=Math.min(...SITE.roads.map(y=>Math.abs(y-p.y)))*SITE.metersPerUnit,water=Math.abs(SITE.waterline-p.y)*SITE.metersPerUnit,neighbors=state.filter(n=>n.id!==p.id&&Math.hypot(n.x-p.x,n.y-p.y)*SITE.metersPerUnit<12),density=Math.min(2,neighbors.length*.15+(p.quantity>15?.3:.05));return {roadDistance:road,waterDistance:water,neighbors:neighbors.map(n=>n.id),density,infectedNeighbors:neighbors.filter(n=>n.infection>15).length};}
function initialState(v){return v.baseline.plants.map((p,i)=>({...clone(p),designVersionId:v.id,health:88,crown:i%5<2?4.6:1.3,stress:0,infection:0,rootDamage:0,protection:0,shade:0,risk:'normal',flowerMonths:[[3,4,5],[7,8,9],[2,3,4,5,6,7,8,9],[5,6,7],[1,2,3,4,5,6,7,8,9,10,11,12]][i%5]}));}
function agents(run,path){const weight=id=>run.knowledgeGraph.edges.find(e=>e.id===id)?.strength??1;const c=path.cycle+1,input=clone(path.state),card=run.cards.find(x=>x.pathId===path.id),env=clone(card.environment.months[c-1]),effects=[],events=[],exposures=[];for(const p of input){const s=spatial(p,input),adapt=p.name==='火焰木',heat=Math.max(0,env.maxC-(adapt?39:34))/5*(env.heatDays/15),drought=Math.max(0,45-env.soilMoisture)/16*(env.dryDays/20)*(p.drip?.28:1),disease=env.diseasePressure*(env.humidity/75)*(1+s.infectedNeighbors*.2+s.density)*(adapt?.7:1),wind=Math.max(0,env.gustMs-20)/12*(1+p.rootDamage/80)*(p.rootProtection?.4:1)*(p.windSupport?.45:1),trample=env.trampling*Math.max(.1,1-s.roadDistance/18)*(p.rootProtection||p.companion?.4:1)*(p.protectionRadius>=5?.5:1),rain=env.waterloggingHours/40*Math.max(.1,1-s.waterDistance/16)*(p.area==='滨水区'?.45:1)*(p.drainage?.3:1);const pressure={heat:heat*weight('heat-'+p.id),drought:drought*weight('drought-'+p.id),disease:disease*weight('disease-'+p.id),wind:wind*weight('wind-'+p.id),trample:trample*weight('trample-'+p.id),rain:rain*weight('rain-'+p.id)};const protection=1-p.protection*.42;let loss=0;for(const [f,val]of Object.entries(pressure)){const d=-val*({heat:1.9,drought:2.8,disease:4.2,wind:7,trample:3.2,rain:3.5}[f])*protection;loss-=d;const e=effect(run,path.id,c,f==='trample'?'Human':'Stress',p.id,'health',d,graph.nodes.find(n=>n.id===f).label+' × 空间暴露 × 耐受');e.graphEdgeIds=[f+'-'+p.id,...(f==='disease'?graph.edges.filter(e=>e.to===p.id&&e.relation==='传播').map(e=>e.id):[])];effects.push(e);}
const total=Object.values(pressure).reduce((a,b)=>a+b,0);effects.push(effect(run,path.id,c,'Plant',p.id,'health',p.health<15?.15:1.3+rng(run.seed,path.id+c+p.id)*.5,'自然恢复与生长'));effects.push(effect(run,path.id,c,'Plant',p.id,'crown',.027-loss*.008-p.stress*.0005,'冠幅生长减去累积胁迫损失'));effects.push(effect(run,path.id,c,'Stress',p.id,'health',-p.stress*.04-p.infection*.07,'累积胁迫滞后'));effects.push(effect(run,path.id,c,'Stress',p.id,'stress',total*3-p.stress*.15,'胁迫累积与释放'));effects.push(effect(run,path.id,c,'Stress',p.id,'infection',disease*5-p.infection*.15,'感染累积与消退'));effects.push(effect(run,path.id,c,'Human',p.id,'rootDamage',trample*5+wind*3-p.rootDamage*.1,'根系暴露累积'));effects.push(effect(run,path.id,c,'Plant',p.id,'protection',-p.protection*.45,'养护保护随时间衰减'));
const predicted=clamp(p.health+effects.filter(e=>e.target===p.id&&e.field==='health').reduce((n,e)=>n+e.delta,0)),dominant=Object.entries(pressure).sort((a,b)=>b[1]-a[1])[0][0];exposures.push({plant:p.id,pressure,spatial:s,dominant,total});if((predicted<60&&(c%3===0||p.health>=60))||loss>5){events.push({id:run.id+'/'+path.id+'/C'+c+'/'+p.id,cycle:c,path:path.id,plant:p.id,title:p.name+'：'+graph.nodes.find(n=>n.id===dominant).label+(predicted<40?'引发严重风险':'累积暴露'),severity:predicted<20?'critical':predicted<40?'high':predicted<60?'medium':'watch',dominant,loss,predicted,graphEdgeIds:[dominant+'-'+p.id]});}}return {cycle:c,input,effects,events,exposures,environment:env,retry:0,checked:false};}
function resolve(state,effects){const next=clone(state),changes=[];for(const e of effects){if(!['health','crown','spacing','stress','infection','rootDamage','protection','x','y'].includes(e.field)||!Number.isFinite(e.delta))throw Error('Schema Gate：Effect字段或数值非法');const p=next.find(x=>x.id===e.target);if(!p)throw Error('Spatial Gate：未知植物');const before=p[e.field]||0;p[e.field]=['health','stress','infection','rootDamage'].includes(e.field)?clamp(before+e.delta):e.field==='protection'?clamp(before+e.delta,0,1):Math.max(e.field==='crown'?.1:0,before+e.delta);changes.push({effectId:e.id,plant:p.id,field:e.field,before,after:p[e.field],delta:p[e.field]-before});}next.forEach(p=>{p.risk=p.health<40?'high':p.health<60?'medium':p.health<75?'watch':'normal';p.shade=clamp(p.crown/5*100);});return {state:next,changes};}
const actions={heat:{name:'遮阳与覆盖',graph:'shade',cost:130,water:0,hours:1.5,heal:4},drought:{name:'定量灌溉与覆盖保湿',graph:'irrigate',cost:110,water:1.1,hours:1,heal:5},disease:{name:'隔离、清除病叶与病害防治',graph:'pest',cost:180,water:.1,hours:2,heal:3},wind:{name:'支撑修剪与危险区域封闭',graph:'support',cost:230,water:0,hours:3,heal:3},trample:{name:'围栏与根系保护',graph:'protect',cost:160,water:0,hours:2,heal:4},rain:{name:'排水疏通与根区检查',graph:'drain',cost:170,water:0,hours:2,heal:4}};
function care(run,path,q,mid){const weight=id=>(run.knowledgeGraph||graph).edges.find(e=>e.id===id)?.strength||1;const limits=clone(run.cards.find(c=>c.pathId===path.id).environment.maintenance);limits.waterM3+=run.design.emergencyWater||0;const used={budget:0,waterM3:0,laborHours:0},rows=[],effects=[];const sorted=[...q.exposures].sort((a,b)=>mid.find(p=>p.id===a.plant).health-mid.find(p=>p.id===b.plant).health);for(const x of sorted){const p=mid.find(p=>p.id===x.plant),a=(run.maintenanceActions||actions)[x.dominant],need=p.health<72||x.total>2,regular=q.cycle%6===0&&!need;let decision='无需处理';if(need){decision=p.health>=65&&x.total<2?'观察':used.budget+a.cost>limits.budget||used.waterM3+a.water>limits.waterM3||used.laborHours+a.hours>limits.laborHours?(p.health<40?'资源不足':'延后'):'执行';}else if(regular)decision=used.budget+12>limits.budget||used.laborHours+.1>limits.laborHours?'延后':'执行';if(decision==='无需处理'&&q.cycle%6!==0)continue;const execute=decision==='执行',cost=execute?(regular?12:a.cost):0,water=execute&&!regular?a.water:0,hours=execute?(regular?.1:a.hours):0;used.budget+=cost;used.waterM3+=water;used.laborHours+=hours;const row={id:run.id+'/'+path.id+'/C'+q.cycle+'/care/'+p.id,path:path.id,cycle:q.cycle,plant:p.id,decision,action:regular?'常规巡检与轻修剪':need?a.name:'维持常规养护',reason:need?`${x.dominant}暴露${x.total.toFixed(2)}；健康${p.health.toFixed(1)}`:'周期巡检',priority:p.health<40?'紧急':need?'优先':'常规',cost,waterM3:water,laborHours:hours,requested:need?{cost:a.cost,waterM3:a.water,laborHours:a.hours}:null,extra:need,beforeHealth:p.health,followUpCycle:q.cycle+2,delayedRecovery:execute&&!regular?a.heal*.45:0,graphEdgeIds:need?[a.graph+'-'+x.dominant]:[],effectIds:[]};if(execute&&!regular){const e=effect(run,path.id,q.cycle,'Maintenance',p.id,'health',2,a.name+'即时影响');e.graphEdgeIds=row.graphEdgeIds;effects.push(e,effect(run,path.id,q.cycle,'Maintenance',p.id,'protection',.7*weight(a.graph+'-'+x.dominant),a.name+'保护期'),effect(run,path.id,q.cycle,'Maintenance',p.id,'stress',-10,a.name+'释放胁迫'));if(x.dominant==='disease')effects.push(effect(run,path.id,q.cycle,'Maintenance',p.id,'infection',-18,'隔离降低感染'));if(['wind','trample'].includes(x.dominant))effects.push(effect(run,path.id,q.cycle,'Maintenance',p.id,'rootDamage',-12,'根系防护'));}rows.push(row);}
for(const h of path.history.filter(h=>h.cycle===q.cycle-2))for(const a of h.care.filter(a=>a.delayedRecovery>0))effects.push(effect(run,path.id,q.cycle,'Maintenance',a.plant,'health',a.delayedRecovery,'延迟恢复：'+a.id));rows.forEach(a=>a.effectIds=effects.filter(e=>e.target===a.plant).map(e=>e.id));return {care:rows,effects,resources:{limits:clone(limits),used}};}
function enrichCard(c){c.environment=environment(c.pathId,+c.horizon);c.conditionSummary=describe(c.environment,Math.min(8,c.horizon));return c;}
function validateEnvironment(c){const errors=[],e=c.environment;if(!e||!Array.isArray(e.months)||e.months.length!==+c.horizon)return ['环境月份数必须与模拟周期一致'];const ranges={maxC:[-10,60],meanC:[-20,55],rainMm:[0,1500],heatDays:[0,31],dryDays:[0,180],humidity:[0,100],soilMoisture:[0,100],waterloggingHours:[0,744],gustMs:[0,90],visitors:[0,100000],trampling:[0,1],diseasePressure:[0,1]};e.months.forEach((m,i)=>{if(m.cycle!==i+1)errors.push('月份cycle必须顺序连续');for(const [k,[lo,hi]]of Object.entries(ranges))if(!Number.isFinite(m[k])||m[k]<lo||m[k]>hi)errors.push('C'+(i+1)+' '+k+'超出范围');if(m.meanC>m.maxC)errors.push('平均温度不得超过最高温度');});if(!e.maintenance||Object.values(e.maintenance).some(x=>!Number.isFinite(x)||x<0))errors.push('养护资源必须为非负数');return [...new Set(errors)];}
function spatialCheck(v){return v.baseline.plants.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=760&&p.y>=0&&p.y<=400);}
function coverage(state){const groups=state.filter(p=>/01|02/.test(p.id)).flatMap(p=>[p,...(p.companionPoint?[{...p,x:p.companionPoint.x,y:p.companionPoint.y,quantity:2}]:[])]),targets=PLANTS.filter(p=>/01|02/.test(p.id));let total=0,covered=0;for(const t of targets)for(let dx=-20;dx<=20;dx+=5)for(let dy=-15;dy<=15;dy+=5){const x=t.x+dx,y=t.y+dy;total++;if(groups.some(p=>Math.hypot(p.x-x,p.y-y)*SITE.metersPerUnit<=p.crown*.5*Math.sqrt(Math.min(6,p.quantity))))covered++;}return covered/total*100;}
const DEFINITIONS=[
['landscape','景观表现',[['shade','关键空间遮阴达标率','%',1,0,100,'覆盖率达到目标下限的周期数 / 全部周期'],['continuity','冠幅覆盖连续性','%',1,0,100,'各周期固定评测网格被冠幅覆盖的比例均值'],['season','季相覆盖','%',1,0,100,'存在健康开花植物的路径月份 / 全部路径月份'],['gap','关键空间缺口率','%',-1,0,100,'100 − 末期关键评测网格冠幅覆盖率']]],
['stability','长期稳定性',[['health','全周期健康水平','分',1,30,95,'所有路径×周期×植物记录健康值均值'],['volatility','健康波动','分',-1,0,30,'逐植物全周期健康标准差的均值'],['recovery','受损后恢复时间','月',-1,0,18,'首次健康<60到恢复≥75的时间；未恢复取剩余观察期并标记删失'],['decline','持续衰退比例','%',-1,0,50,'连续3次健康下降超过1分的植物窗口 / 全部植物窗口']]],
['resilience','风险与环境承受度',[['exposure','高风险暴露时长占比','%',-1,0,50,'健康<40的植物周期 / 全部植物周期'],['severe','严重风险发作数量','次/路径',-1,0,30,'植物首次进入健康<40的次数，按路径平均'],['failure','极端事件失效比例','%',-1,0,60,'极端环境周期健康<40记录 / 极端环境全部植物记录'],['worst','跨路径最差健康','分',1,20,90,'各路径全周期健康均值的最小值']]],
['maintenance','养护压力',[['frequency','额外干预频次','次/路径年',-1,0,180,'额外执行动作数 / 路径模拟年数后平均'],['resources','额外资源需求','资源单位/路径年',-1,0,1500,'(额外水量m³ + 工时×5) / 路径模拟年数后平均'],['overload','资源不足或延后比例','%',-1,0,70,'资源不足与延后动作 / 全部额外需求动作'],['efficacy','干预后观测改善率','%',1,0,100,'两个月后健康比执行前提升≥2分的动作 / 可观察动作；非因果归因']]],
['cost','全周期成本',[['construction','建设成本','元',-1,40000,85000,'当前版本冻结建设成本'],['maintenanceCost','累计养护成本','元/情景',-1,0,50000,'各路径实际执行成本之和的等权情景均值'],['rework','预计返工成本','元/情景',-1,0,60000,'Σ(事项情景风险权重 × 冻结标准返工成本)，路径等权平均；不是概率'],['deltaCost','相对原方案成本变化','%',-1,-30,60,'(本版本全周期成本 − V1全周期成本)/V1成本；V1为0']]]
];
function evaluationSpec(){return {version:'evaluation-3.0',source:SOURCE,weighting:'每维度内4项等权；不计算跨维度总分',missing:'子指标缺失则维度不可计算，不重新分配权重',dimensions:clone(DEFINITIONS),standardCosts:{replacement:4000,rehabilitation:1200},riskWeights:'highPlantMonths/horizon × replacement + rootDamage/100 × rehabilitation',mapping:'higher: clamp((raw-min)/(max-min)*100); lower: 100-higher'};}
function evaluate(run,spec=run.evaluationSpec){if(run.status!=='complete')throw Error('运行完成后才能评价');const signature=JSON.stringify(spec);if(run.evaluation?.signature===signature)return run.evaluation;const all=run.paths.flatMap(p=>p.history),states=all.flatMap(h=>h.state),cares=all.flatMap(h=>h.care),extra=cares.filter(c=>c.extra),done=extra.filter(c=>c.decision==='执行'),covers=all.map(h=>coverage(h.state)),perPath=run.paths.map(p=>({pathId:p.id,health:mean(p.history.flatMap(h=>h.state.map(p=>p.health))),exposure:p.history.flatMap(h=>h.state).filter(p=>p.health<40).length/(p.history.length*p.state.length)*100})),vol=[],recovery=[],censored=[],episodes=[],declines=[];for(const path of run.paths)for(const plant of path.state){const seq=path.history.map(h=>h.state.find(p=>p.id===plant.id).health),avg=mean(seq);vol.push(Math.sqrt(mean(seq.map(x=>(x-avg)**2))));const start=seq.findIndex(x=>x<60);if(start>=0){const recovered=seq.findIndex((x,i)=>i>start&&x>=75);recovery.push(recovered<0?seq.length-start:recovered-start);if(recovered<0)censored.push({path:path.id,plant:plant.id});}episodes.push(seq.filter((x,i)=>x<40&&(i===0||seq[i-1]>=40)).length);for(let i=3;i<seq.length;i++)declines.push(seq[i]<seq[i-1]-1&&seq[i-1]<seq[i-2]-1&&seq[i-2]<seq[i-3]-1?1:0);}
const extreme=all.filter(h=>h.environment&&(h.environment.maxC>=38||h.environment.gustMs>=30||h.environment.waterloggingHours>=48)).flatMap(h=>h.state),observable=done.map(c=>{const p=run.paths.find(p=>p.id===c.path),h=p.history.find(h=>h.cycle===c.followUpCycle);return h?{action:c,after:h.state.find(x=>x.id===c.plant).health}:null;}).filter(Boolean),maintenanceCost=mean(run.paths.map(p=>p.history.flatMap(h=>h.care).reduce((n,c)=>n+c.cost,0))),reworkItems=run.paths.flatMap(path=>path.state.map(p=>{const months=path.history.filter(h=>h.state.find(x=>x.id===p.id).health<40).length,weight=months/path.horizon,structural=p.rootDamage/100;return {pathId:path.id,plantId:p.id,highMonths:months,weight,structural,standardCost:spec.standardCosts.replacement,value:weight*spec.standardCosts.replacement+structural*spec.standardCosts.rehabilitation};})),rework=reworkItems.reduce((n,x)=>n+x.value,0)/run.paths.length,total=run.design.cost+maintenanceCost+rework;
const values={shade:mean(covers.map(x=>x>=run.goal.shade?100:0)),continuity:mean(covers),season:mean(all.map(h=>h.state.some(p=>p.health>=60&&p.flowerMonths.includes((h.cycle-1)%12+1))?100:0)),gap:100-mean(run.paths.map(p=>coverage(p.state))),health:mean(states.map(p=>p.health)),volatility:mean(vol),recovery:recovery.length?mean(recovery):0,decline:declines.length?mean(declines)*100:0,exposure:states.filter(p=>p.health<40).length/states.length*100,severe:episodes.reduce((n,x)=>n+x,0)/run.paths.length,failure:extreme.length?extreme.filter(p=>p.health<40).length/extreme.length*100:null,worst:Math.min(...perPath.map(p=>p.health)),frequency:mean(run.paths.map(p=>p.history.flatMap(h=>h.care).filter(c=>c.extra&&c.decision==='执行').length/(p.horizon/12))),resources:mean(run.paths.map(p=>p.history.flatMap(h=>h.care).filter(c=>c.extra).reduce((n,c)=>n+c.waterM3+c.laborHours*5,0)/(p.horizon/12))),overload:extra.length?extra.filter(c=>['延后','资源不足'].includes(c.decision)).length/extra.length*100:0,efficacy:observable.length?observable.filter(x=>x.after>=x.action.beforeHealth+2).length/observable.length*100:null,construction:run.design.cost,maintenanceCost,rework,deltaCost:run.evaluationBaselineTotal?(total/run.evaluationBaselineTotal-1)*100:0};
const calls=[],dimensions=spec.dimensions.map(([id,name,defs])=>{const metrics=defs.map(([key,label,unit,direction,min,max,formula])=>{const raw=values[key],score=raw==null?null:clamp((raw-min)/(max-min)*100)*(direction===1?1:-1)+(direction===1?0:100),worst=perPath.slice().sort((a,b)=>a.health-b.health)[0],path=run.paths.find(p=>p.id===worst.pathId),h=path.history.slice().sort((a,b)=>mean(a.state.map(p=>p.health))-mean(b.state.map(p=>p.health)))[0],plant=h.state.slice().sort((a,b)=>a.health-b.health)[0];const call={id:run.id+'/evaluation/'+key,tool:'EvaluationTools.'+key,ruleVersion:spec.version,input:{runId:run.id,paths:run.paths.map(p=>p.id),cycles:run.paths.map(p=>p.horizon),plantRecords:states.length,actionRecords:cares.length},formula,thresholds:{min,max,direction},raw:raw==null?null:+raw.toFixed(2),score:score==null?null:+score.toFixed(1),unit,weight:.25,missing:raw==null?'无符合条件的观察样本':null,evidence:{runId:run.id,path:worst.pathId,cycle:h.cycle,plant:plant.id},details:key==='rework'?reworkItems:key==='recovery'?{censored,count:recovery.length}:key==='efficacy'?{observable:observable.length,window:2}:null};calls.push(call);return {key,label,...call};});return {id,name,metrics,score:metrics.some(m=>m.score===null)?null:+mean(metrics.map(m=>m.score)).toFixed(1)};});const result={version:spec.version,signature,dimensions,calls,perPath,values,total,summary:{health:values.health,crown:mean(run.paths.flatMap(p=>p.state.map(x=>x.crown))),highRisk:new Set(states.filter(p=>p.health<40).map(p=>p.id)).size,care:done.length,construction:run.design.cost,rework,maintenanceCost,total,shade:values.continuity}};if(spec===run.evaluationSpec)run.evaluation=result;return result;}
return {SITE,RULE,SOURCE,graph,environment,describe,layout,spatial,initialState,agents,resolve,care,enrichCard,validateEnvironment,spatialCheck,coverage,evaluationSpec,evaluate,DEFINITIONS,actions};
}
if(typeof module!=='undefined'&&module.exports)module.exports=PlantSimDomain;else root.PlantSimDomain=PlantSimDomain;
})(typeof window==='undefined'?globalThis:window);
