/* PlantSim offline domain model. Agents are pure; only StateResolver writes plant states.
 * Demo rules and species substitutions are illustrative, not botanical advice. */
(function(root){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const freeze=x=>{if(x&&typeof x==='object'){Object.freeze(x);Object.values(x).forEach(freeze);}return x;};
const PLANTS=[
['A01','入口区','秋枫','Bischofia javanica',3,'胸径15cm'],['A02','入口区','铁冬青','Ilex rotunda',2,'胸径12cm'],['A03','入口区','朱槿','Hibiscus rosa-sinensis',8,'高80cm'],['A04','入口区','短穗鱼尾葵','Caryota mitis',4,'高2.5m'],['A05','入口区','马尼拉草','Zoysia matrella',200,'m²草皮'],
['B01','滨水区','落羽杉','Taxodium distichum',5,'胸径18cm'],['B02','滨水区','水石榕','Elaeocarpus hainanensis',3,'胸径10cm'],['B03','滨水区','花叶芦竹','Arundo donax',15,'高1.5m'],['B04','滨水区','香蒲','Typha orientalis',20,'高1.2m'],['B05','滨水区','千屈菜','Lythrum salicaria',30,'高80cm'],
['C01','步道区','阴香','Cinnamomum burmannii',6,'胸径14cm'],['C02','步道区','红花羊蹄甲','Bauhinia blakeana',4,'胸径12cm'],['C03','步道区','九里香','Murraya paniculata',12,'高1m'],['C04','步道区','栀子','Gardenia jasminoides',10,'高60cm'],['C05','步道区','大花萱草','Hemerocallis hybrida',50,'高50cm'],
['D01','休息区','榕树','Ficus microcarpa',1,'胸径30cm'],['D02','休息区','四季桂','Osmanthus fragrans',3,'高2m'],['D03','休息区','朱蕉','Cordyline fruticosa',10,'高80cm'],['D04','休息区','龟背竹','Monstera deliciosa',8,'高1m'],['D05','休息区','翠竹','Sasa pygmaea',30,'高50cm']
].map((r,i)=>({id:r[0],area:r[1],name:r[2],latin:r[3],quantity:r[4],spec:r[5],x:65+(i%5)*137,y:[85,330,170,250][Math.floor(i/5)],source:{file:'植物清单.xlsx',row:i+2,cad:'plant-layer/'+r[0],photo:'现场复核记录 p.'+(i+1),confidence:i===0?.72:i%7===0?.86:.96},spacing:2.5,drip:false,rootProtection:false}));
const PATHS=[['A1','正常年份',0,'正常温度、降水与人流','常态生长'],['A2','轻微波动',.25,'局部高温1–2个月，人流略增','短时波动'],['A3','春旱与夏季高温',.6,'春季干旱、夏季持续高温','水分压力'],['B1','持续高温',.9,'夏季+2.8°C，降水−20%','水分与热胁迫'],['B2','高温叠加病害',1,'高温、少雨、病害重复暴露','复合健康风险'],['C1','台风与高人流',.8,'台风、高温、人流踩踏','根系与结构损伤']].map(r=>({id:r[0],name:r[1],severity:r[2],conditions:r[3],risk:r[4]}));
const EVENTS=[
{cycle:8,path:'B1',plant:'B05',title:'千屈菜水分压力',target:68,action:'自动浇水',decision:'执行',recovery:7},
{cycle:12,path:'B2',plant:'A01',title:'入口乔木叶斑病爆发',target:52,action:'喷药与修剪',decision:'执行',recovery:8},
{cycle:16,path:'C1',plant:'C01',title:'人流踩踏导致根系受损',target:49,action:'设置围栏',decision:'执行',recovery:9},
{cycle:20,path:'B1',plant:'A01',title:'入口东侧3株乔木持续衰退',target:15,action:'浇水与遮阳',decision:'执行',recovery:16},
{cycle:24,path:'B2',plant:'A01',title:'入口乔木二次衰退',target:28,action:'观察病害进展',decision:'观察',recovery:0},
{cycle:24,path:'B2',plant:'B01',title:'落羽杉高温适应性下降',target:57,action:'增加灌溉',decision:'执行',recovery:5},
{cycle:28,path:'C1',plant:'D01',title:'台风导致枝干损伤',target:29,action:'支撑与修剪',decision:'执行',recovery:10},
{cycle:32,path:'A3',plant:'C02',title:'春旱累积影响显现',target:67,action:'自动浇水',decision:'执行',recovery:10}];
const DEFAULT_TEXT='未来36个月遮阴覆盖率维持60%以上，重点评估高温、台风、病虫害和人流踩踏；养护预算不增加，不使用外来入侵物种。';
const D=(typeof module!=='undefined'&&module.exports?require('./plantsim-domain.js'):root.PlantSimDomain)({clone,PLANTS,PATHS,rng,effect});
function newProject(name='华南滨水公园植物景观未来模拟',location='华南某城市滨水区域',area=3.2){return {id:'project-1',name,location,area,climate:'南亚热带季风气候',sessionId:'session-1',imports:[],stage:0,goals:[],cards:[],versions:[{id:'V1',parentId:null,note:'原方案',createdAt:new Date().toISOString(),status:'draft',spatial:clone(D.SITE),layoutChanges:[],baseline:{id:'baseline-V1',confirmed:false,conflicts:[{id:'quantity-A01',plant:'A01',excel:3,cad:2,resolved:false}],plants:clone(PLANTS)},cost:45000}],runs:[],regression:[],adoption:null,messages:[],nextRun:1};}
function importFiles(project,names){project.imports=(names&&names.length?names:['场地总图.dwg','场地边界.geojson','植物清单.xlsx','需求说明.docx','现场照片.jpg']).map((name,i)=>({id:'file-'+i,name,status:'parsed',fields:[42,18,120,14,20][i%5],parser:'offline-mock'}));project.stage=2;}
function resolveConflict(v,quantity){if(!Number.isInteger(quantity)||quantity<1||quantity>100)throw Error('数量须为1–100的整数');v.baseline.plants[0].quantity=quantity;v.baseline.plants[0].source.confidence=1;v.baseline.conflicts[0].resolved=true;v.baseline.conflicts[0].chosen=quantity;}
function confirmBaseline(project,v){if(!D.spatialCheck(v))throw Error('Spatial Gate：植物坐标越界');if(!project.imports.length||v.baseline.conflicts.some(c=>!c.resolved))throw Error('Input Gate：资料未导入或冲突未解决');v.baseline.confirmed=true;v.status='ready';project.stage=4;}
function parseGoal(text){const months=text.match(/(\d+)\s*个?月/),years=text.match(/(\d+)\s*年/);return {text,horizon:months?+months[1]:years?+years[1]*12:36,focus:['冠幅','健康度','风险','景观效果'],risks:['高温','台风','病虫害','踩踏'].filter(x=>text.includes(x)),constraints:text.includes('预算')||text.includes('养护')?'养护预算不增加；不使用入侵物种':'不使用入侵物种',shade:+(text.match(/(\d+)\s*%/)||[,60])[1]};}
function saveGoal(p,goal){if(p.status==='completed')throw Error('项目已完成，请先继续优化');if(!Number.isInteger(+goal.horizon)||goal.horizon<1||goal.horizon>60||goal.shade<0||goal.shade>100||!goal.focus.length)throw Error('目标需包含1–60个月、0–100%遮阴与关注指标');const g=freeze({...clone(goal),horizon:+goal.horizon,id:'goal-'+(p.goals.length+1),createdAt:new Date().toISOString()});p.goals.push(g);p.cards=PATHS.map(x=>({id:'task-'+x.id,pathId:x.id,horizon:g.horizon,conditions:x.conditions,activeFactors:x.risk,riskContext:x.risk,maintenance:'月度预算上限1000；优先保命与安全',timeline:'C8/C12/C16/C20/C24/C28/C32',focus:g.focus.join('、'),constraints:g.constraints,revision:1,frozen:false,gate:null}));p.cards.forEach(D.enrichCard);return g;}
function validateCard(c){const errors=[];if(!Number.isInteger(+c.horizon)||c.horizon<1||c.horizon>60)errors.push('周期必须为1–60个月');for(const k of ['conditions','activeFactors','riskContext','maintenance','timeline','focus','constraints'])if(!String(c[k]||'').trim())errors.push(k+'不能为空');errors.push(...D.validateEnvironment(c));c.gate={id:'gate-task-'+c.pathId+'-'+c.revision,type:'TaskCard',passed:!errors.length,errors};return c.gate;}
function updateCard(c,patch){if(c.frozen)throw Error('请先解冻任务卡');Object.assign(c,patch);c.revision++;c.gate=null;}
function freezeCard(c){if(!validateCard(c).passed)throw Error(c.gate.errors.join('；'));c.frozen=true;}
function createVersion(p,base,patch={}){const id='V'+(p.versions.length+1),v=clone(base);v.id=id;v.parentId=base.id;v.note=patch.note||'设计修订';v.createdAt=new Date().toISOString();v.status='draft';v.baseline.id='baseline-'+id;v.baseline.confirmed=false;const a=v.baseline.plants.find(x=>x.id==='A01');a.name=patch.species||'火焰木';a.latin=a.name==='火焰木'?'Spathodea campanulata':a.latin;const oldSpacing=a.spacing;a.spacing=Number(patch.spacing||a.spacing);a.x+=(a.spacing-oldSpacing)*20;if(!Number.isFinite(a.spacing)||a.spacing<1||a.spacing>10)throw Error('间距须为1–10米');if(patch.comprehensive){const b=v.baseline.plants.find(x=>x.id==='B03');b.quantity=10;b.drip=true;const c=v.baseline.plants.find(x=>x.id==='C01');c.quantity=4;c.companion='樟树 ×2';v.baseline.plants.find(x=>x.id==='D01').rootProtection=true;}v.cost=45000+(a.name!=='秋枫'?7000:0)+(patch.comprehensive?6000:0);D.layout(v,base,patch);p.versions.push(v);return v;}
function initialState(v){return D.initialState(v);}
const risk=h=>h<40?'high':h<60?'medium':h<75?'watch':'normal';
function rng(seed,key){let h=seed;for(const c of key)h=Math.imul(h^c.charCodeAt(0),16777619);return (h>>>0)/4294967296;}
function effect(run,path,cycle,agent,target,field,delta,reason){return {id:[run.id,path,cycle,agent,target,field,Math.floor(rng(17,reason)*4294967296).toString(36)].join('/'),pathId:path,cycle,agent,tool:agent==='Plant'?'growth_lookup':agent==='Stress'?'stress_assess':agent==='Human'?'exposure_lookup':agent==='Repair'?'constraint_repair':'maintenance_policy',target,field,delta,reason};}
function agents(run,path){return D.agents(run,path);}
function StateResolver(state,effects){return D.resolve(state,effects);}
function newRun(p,v,reference){if(p.status==='completed')throw Error('项目已完成，请先继续优化');if(!v.baseline.confirmed)throw Error('Input Gate：请先确认基线');if(!p.goals.length||!p.cards.length||p.cards.some(c=>!c.frozen))throw Error('所有目标与任务卡必须确认并冻结');const id='run-'+p.nextRun++,cards=clone(reference?reference.cards:p.cards),goal=clone(reference?reference.goal:p.goals.at(-1));const run={id,versionId:v.id,design:clone(v),goal,cards,seed:reference?reference.seed:9032026,ruleVersion:reference?reference.ruleVersion:D.RULE,status:'ready',replayOf:null,failures:[],logs:[],createdAt:new Date().toISOString(),paths:cards.map(c=>({id:c.pathId,cycle:0,horizon:+c.horizon,state:initialState(v),history:[],pending:null,blocked:null}))};run.maintenanceActions=clone(reference?.maintenanceActions||D.actions);run.evaluationSpec=clone(reference?reference.evaluationSpec:D.evaluationSpec());run.knowledgeGraph=clone(reference?reference.knowledgeGraph:D.graph);run.evaluationBaselineTotal=reference?(reference.evaluationBaselineTotal||D.evaluate(reference).total):null;run.fairness=JSON.stringify({cards,goal,seed:run.seed,rule:run.ruleVersion,evaluation:run.evaluationSpec,knowledge:run.knowledgeGraph,maintenanceActions:run.maintenanceActions});p.runs.push(run);return run;}
function log(run,path,cycle,type,text,data){const e={id:run.id+'/trace-'+(run.logs.length+1),runId:run.id,pathId:path,cycle,type,text,data:clone(data||{})};run.logs.push(e);return e;}
function scheduledGate(path,pending){const c=pending.cycle;if(path.id==='A1'&&c===3)return {type:'Spatial',node:'Human',description:'候选位置 A01/A02 间距1.7m，小于2m',plant:'A02'};if(path.id==='A2'&&c===6)return {type:'Schema',node:'Stress',description:'Stress Effect.delta 返回字符串，要求有限数值',plant:'A01'};if(path.id==='B2'&&c===12)return {type:'Business',node:'Maintenance',description:'C01建议养护1500，超过月度预算1000',plant:'C01'};if(path.id==='B1'&&c===20)return {type:'Numeric',node:'Stress',description:'输出health_delta=-150，超过单次变更允许范围[-100,100]',plant:'A01'};return null;}
function prepare(run,p){p.pending=agents(run,p);const q=p.pending;['Plant','Stress','Human'].forEach(a=>log(run,p.id,q.cycle,'Agent',a+' → Effect',{agent:a,tool:q.effects.find(e=>e.agent===a)?.tool,effects:q.effects.filter(e=>e.agent===a)}));if((p.id==='A2'&&q.cycle===5)||(p.id==='A3'&&q.cycle===10)){log(run,p.id,q.cycle,'ToolRetry',p.id==='A2'?'Tool timeout → 自动Retry成功':'Model格式异常 → 自动Repair成功',{retry:1,maxRetries:2,quiet:true});}const gate=scheduledGate(p,q);if(gate){if(gate.type==='Schema'){q.badEffect=q.effects.find(e=>e.agent==='Stress');q.originalDelta=q.badEffect.delta;q.badEffect.delta='invalid';}if(gate.type==='Spatial'){const a=q.input.find(x=>x.id==='A01'),b=q.input.find(x=>x.id==='A02');q.effects.push(effect(run,p.id,q.cycle,'Human','A02','x',a.x+6.8-b.x,'候选位置'),effect(run,p.id,q.cycle,'Human','A02','y',a.y-b.y,'候选位置'));}if(gate.type==='Numeric'){q.badNumeric=q.effects.find(e=>e.target==='A01'&&e.field==='health'&&e.agent==='Stress');q.numericOriginal=q.badNumeric.delta;q.badNumeric.delta=-150;}if(gate.type==='Business')q.proposedMaintenanceCost=1500;
const candidate=gate.type==='Schema'?null:StateResolver(q.input,q.effects);const failed=gate.type==='Schema'||gate.type==='Spatial'||gate.type==='Business'||gate.type==='Numeric';if(failed){const f={id:run.id+'/failure-'+(run.failures.length+1),pathId:p.id,cycle:q.cycle,...gate,status:'FAILED',retry:0,maxRetries:2,checkpointId:run.id+'/'+p.id+'/c'+q.cycle+'/'+gate.node,checkpoint:clone(q),stages:['FAILED']};run.failures.push(f);p.blocked=f.id;log(run,p.id,q.cycle,'FailureEvent',gate.type+' Gate阻断',f);}}}
function commit(run,p){const q=p.pending,mid=StateResolver(q.input,q.effects),careResult=D.care(run,p,q,mid.state),final=StateResolver(mid.state,careResult.effects);const record={cycle:q.cycle,pathId:p.id,input:clone(q.input),effects:clone(q.effects),intermediate:mid.state,maintenance:careResult.effects,care:careResult.care,resources:careResult.resources,environment:clone(q.environment),exposures:clone(q.exposures),changes:[...mid.changes,...final.changes],state:final.state,events:q.events,gates:['Schema','Spatial','Numeric','Business'].map(type=>({type,passed:true})),checkpoint:clone(q)};p.state=clone(final.state);p.history.push(record);p.cycle=q.cycle;p.pending=null;log(run,p.id,p.cycle,'Resolver','Intermediate → Maintenance → Final State',{changes:record.changes,care:record.care,effects:record.maintenance});}
function tick(run){if(['complete','paused','failed'].includes(run.status))return;run.status='running';for(const p of run.paths){if(p.blocked||p.cycle>=p.horizon)continue;if(!p.pending)prepare(run,p);if(!p.blocked)commit(run,p);}if(run.paths.every(p=>p.cycle>=p.horizon))run.status='complete';else if(run.paths.every(p=>p.blocked||p.cycle>=p.horizon))run.status='blocked';}
function repair(run,failureId){const f=run.failures.find(x=>x.id===failureId),p=run.paths.find(x=>x.id===f?.pathId);if(!f||!p?.blocked)throw Error('没有待恢复节点');if(f.retry>=2){f.status='EXHAUSTED';run.status='failed';throw Error('已达到2次重试上限');}const q=p.pending;f.retry++;f.stages.push('LOCATING','MIN_ROLLBACK','REPAIRING');if(f.type==='Schema')q.badEffect.delta=q.originalDelta;if(f.type==='Spatial'){const e=q.effects.find(e=>e.field==='x');e.delta=q.input.find(x=>x.id==='A01').x+8.8-q.input.find(x=>x.id==='A02').x;e.reason='Repair：局部位置修正';}if(f.type==='Business')q.proposedMaintenanceCost=500;if(f.type==='Numeric')q.badNumeric.delta=q.numericOriginal;
// Validate the repaired candidate. Unaffected agents and all earlier states are retained.
const candidate=StateResolver(q.input,q.effects);if(candidate.state.some(p=>!Number.isFinite(p.health)))throw Error('修复校验失败');f.stages.push('VALIDATING','RESUME');f.status='RECOVERED';p.blocked=null;q.retry=f.retry;log(run,p.id,q.cycle,'Retry','最小回退 → Repair → Gate通过 → 恢复',{failureId:f.id,retry:f.retry,checkpointId:f.checkpointId,stages:f.stages});run.status='running';}
function complete(run){let guard=0;while(run.status!=='complete'&&guard++<200){if(run.status==='paused')run.status='running';tick(run);run.failures.filter(f=>f.status==='FAILED').forEach(f=>repair(run,f.id));}if(run.status!=='complete')throw Error('运行未完成');return run;}
function replay(p,source,pathId,cycle){if(source.archived)throw Error('归档不包含Checkpoint，请同条件重跑');const original=source.paths.find(x=>x.id===pathId),record=original.history.find(x=>x.cycle===cycle);if(!record)throw Error('该周期尚无Checkpoint');const id='run-'+p.nextRun++,r=clone(source);r.id=id;r.replayOf={runId:source.id,pathId,cycle};r.status='ready';r.failures=[];r.logs=[];delete r.evaluation;r.paths=r.paths.filter(x=>x.id===pathId);const path=r.paths[0];path.history=clone(original.history.filter(x=>x.cycle<cycle));path.state=clone(record.input);path.cycle=cycle-1;path.pending=clone(record.checkpoint);path.blocked=null;p.runs.push(r);log(r,pathId,cycle,'Checkpoint','从原运行Checkpoint派生回放，不改写原记录',r.replayOf);return r;}
function latestRun(p,v){return [...p.runs].reverse().find(r=>r.versionId===v&&r.status==='complete'&&!r.replayOf);}
function metrics(run){const m=D.evaluate(run).summary;return Object.fromEntries(Object.entries(m).map(([k,v])=>[k,typeof v==='number'?+v.toFixed(2):v]));}
function compare(runs){if(runs.length<2||runs.length>3)throw Error('请选择2–3个已完成版本');if(runs.some(r=>r.status!=='complete'||r.replayOf)||new Set(runs.map(r=>r.versionId)).size!==runs.length)throw Error('仅可比较不同设计的完整运行');if(new Set(runs.map(r=>r.fairness)).size!==1)throw Error('未来条件、目标、规则或seed不同，不能公平比较');return runs.map(r=>({versionId:r.versionId,runId:r.id,...metrics(r)}));}
const API={domain:D,evaluate:D.evaluate,clone,freeze,PLANTS,PATHS,EVENTS,DEFAULT_TEXT,newProject,importFiles,resolveConflict,confirmBaseline,parseGoal,saveGoal,validateCard,updateCard,freezeCard,createVersion,newRun,tick,repair,complete,replay,latestRun,metrics,compare,StateResolver,risk,agents};
// API adapter boundary: replace these methods with real services in a future version.
API.adapter={mode:'offline-rules',parse:importFiles,simulate:tick,chat:{mode:'not-connected',async *stream(){throw Error('本轮未接入真实模型；请使用明确标注的离线规则演示');},cancel(){},retry(){throw Error('未配置模型服务');}}};
(typeof module!=='undefined'&&module.exports?require('./plantsim-business.js'):root.PlantSimBusiness)(API);
if(typeof module!=='undefined'&&module.exports)module.exports=API;else root.PlantSimEngine=API;
})(typeof window==='undefined'?globalThis:window);
